### ISSUE TITLE
[Bug] 🐛 历史记录过长导致展开键超出屏幕

### ISSUE THREAD

**Issue by YuenSzeHong** [Harry-zklcdc/go-proxy-bingai#146]
### Describe the bug

历史记录过长导致展开键超出屏幕

### Steps to reproduce

打开任何历史记录

### Expected behavior

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/a9d751c2-0648-429d-8ec8-fe0de96f423a)

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/40477634/56901024-410c-40fd-a2bd-33ea34437d4b)

### Versions

- OS: 
- Browser & Version: 
- GoProxiBing Version: 

### Additional context

#47
```css
.main {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    overflow: hidden;
    height: 100vh;
}
```

**Comment by Harry-zklcdc** [comment]
![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21104213/a9f2b2da-ed68-4084-88e9-4b4676f78968)
我这没有这样的情况呢

**Comment by YuenSzeHong** [comment]
> ![image](https://user-images.githubusercontent.com/21104213/261543675-a9f2b2da-ed68-4084-88e9-4b4676f78968.png) 我这没有这样的情况呢

huggingface部署

**Comment by skyfly2000** [comment]
mac 的safari特别明显，对话记录超出屏幕后（或者多到一定数量后），点“更多聊天记录”，右侧会一片空白。只有架梯子到原版去删除对话。 @Harry-zklcdc

**Comment by ilanks** [comment]
.scroller {
    position: relative;
    box-sizing: border-box;
    padding: 16px;
    max-block-size: max(324px, 60%);
    height: 100vh;  //增加这个高度就可以解决
}

**Comment by sanjinbot** [comment]
我的也有这个问题vercel部署的，到edge浏览器，1080的分辨率，就跟楼主图二一样，就是看不到所有聊天这个按钮，而且手机端看不到历史聊天记录，不知道是不是我的问题

**Comment by Harry-zklcdc** [comment]
> mac 的safari特别明显，对话记录超出屏幕后（或者多到一定数量后），点“更多聊天记录”，右侧会一片空白。只有架梯子到原版去删除对话。 @Harry-zklcdc

手上没有Safari的浏览器🤣，等我啥时候买个Mac试试

**Comment by Harry-zklcdc** [comment]
> .scroller { position: relative; box-sizing: border-box; padding: 16px; max-block-size: max(324px, 60%); height: 100vh; //增加这个高度就可以解决 }

这个代码目前已经在代码里面了

https://github.com/Harry-zklcdc/go-proxy-bingai/blob/b061f9752244afa5d4f79c7cc9c66355f82fd473/frontend/src/stores/modules/user/index.ts#L72-L73

**Comment by YuenSzeHong** [comment]
> .scroller { position: relative; box-sizing: border-box; padding: 16px; max-block-size: max(324px, 60%); height: 100vh; //增加这个高度就可以解决 }

得设在main上
```css
.main {
    display: flex;
    flex-direction: column;
    flex-grow: 1;
    overflow: hidden;
    height: 100vh;
}
```
