### ISSUE TITLE
[Help] 🤔  使用 Docker 部署在国内服务器上，发现没办法使用

### ISSUE THREAD

**Issue by cy920820** [Harry-zklcdc/go-proxy-bingai#181]
### Describe the help wanted

使用 docker-compose 部署到国内服务器，能打开网页，但是提问无法得到响应

docker-compose.yml 
```yml
version: '3'
  
services:
  go-proxy-bingai:
    # 镜像名称
    image: zklcdc/go-proxy-bingai
    # 容器名称
    container_name: go-proxy-bingai
    # 自启动
    restart: always
    # volumes:
    #   # 将编译好的二进制文件 (linux-amd64) 放到和 docker-compose.yml 同个文件夹, 并赋予可执行权限 (`chmod +x go-proxy-bingai`)
    #   - $PWD/go-proxy-bingai:/app/go-proxy-bingai
    ports:
      - 7000:8080
    # environment:
    #   - USER_KievRPSSecAuth=xxx
    #   - Go_Proxy_BingAI_SOCKS_URL=192.168.0.88:1070
    #   - Go_Proxy_BingAI_SOCKS_USER=xxx
    #   - Go_Proxy_BingAI_SOCKS_PWD=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_1=xxx
    #   - Go_Proxy_BingAI_USER_TOKEN_2=xxx
```

### Steps to behave

反向代理都都正常访问，但是提问都显示 302

### Expected behavior

期望请求都是 200

### Screenshots

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21211512/d2966f74-b20d-4db1-b3f4-ed10fd60c4e9)

![image](https://github.com/Harry-zklcdc/go-proxy-bingai/assets/21211512/54c8fb78-774c-4687-805b-0d70734609d1)

### Versions

- OS: MacOS 13.5.1
- Browser & Version:  chrome 116.0.5845.110
- GoProxiBing Version:  latest
