### ISSUE TITLE
[Bug] 🐛 无法请求ByPass服务器

### ISSUE THREAD

**Issue by wuyu8512** [Harry-zklcdc/go-proxy-bingai#369]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

日志显示
```
Get "http://go-bingai-pass:7860/gettoken": dial tcp 172.29.0.3:7860: connect: connection refused
```

但我可以直接容器内正常 `wget http://go-bingai-pass:7860/gettoken`

### Steps to reproduce

```
version: '3'

services:
  go-proxy-bingai:
    image: zklcdc/go-proxy-bingai
    container_name: go-proxy-bingai  
    restart: always
    environment:
      - BYPASS_SERVER=http://go-bingai-pass:7860
      # - BING_BASE_URL=https://www.bing.com
      # - SYDNEY_BASE_URL=https://sydney.bing.com
      # - HTTP_PROXY=http://172.17.0.1:18080
      # - HTTPS_PROXY=http://172.17.0.1:18080

  go-bingai-pass:
    image: zklcdc/go-bingai-pass
    container_name: go-bingai-pass
    restart: always
    environment:
      - PROXY_SERVER=http://0.0.0.0:7860
      - PASS_TIMEOUT=3
      - HEADLESS=false
```

### Expected behavior

正常请求

### Deploy

Docker

### OS & Version

Ubuntu

### Browser & Version

Chrome

### GoProxiBingAI Version

latest

**Comment by Harry-zklcdc** [comment]
https://github.com/Harry-zklcdc/go-proxy-bingai/issues/365#issuecomment-1983655775

```yaml
go-proxy-bingai:
  environment:
    - BYPASS_SERVER=http://172.17.0.1:7860
```
这玩意别改
