### ISSUE TITLE
[Bug] 🐛 Docker部署后显示 您似乎是盗版软件受害者

### ISSUE THREAD

**Issue by cr-zhichen** [Harry-zklcdc/go-proxy-bingai#425]
### Confirmations

- [X] 我确认我已经仔细阅读了 [Wiki](https://github.com/Harry-zklcdc/go-proxy-bingai/wiki), 并且已经搜索了已有的 issue, 并没有类似问题。

### Describe the bug

使用仓库中的`docker-compose`部署后提示`您似乎是盗版软件受害者`
![显示](https://img-cdn.ccrui.cn/2024/05/30/665885b0de23a.png)

### Steps to reproduce

使用以下`docker-compose.yml`部署，使用Nginx反向代理
``` 
version: "3"

services:
  go-bingai-bypass:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3990:7860
    environment:
      - PASS_TIMEOUT=8

  go-proxy-bingai:
    image: zklcdc/go-proxy-bingai
    container_name: go-proxy-bingai
    restart: always
    ports:
      - 3991:8080
    environment:
      - BYPASS_SERVER=https://bing-pass.ccrui.cn
      # - BING_BASE_URL=https://www.bing.com
      # - SYDNEY_BASE_URL=https://sydney.bing.com
      # - HTTP_PROXY=http://172.17.0.1:18080
      # - HTTPS_PROXY=http://172.17.0.1:18080
      # - Go_Proxy_BingAI_USER_TOKEN_1=xxx
      # - Go_Proxy_BingAI_USER_TOKEN_2=xxx
      # - USER_KievRPSSecAuth=xxx
      # - USER_RwBf=xxx
      # - USER_MUID=xxx
      # - APIKEY=sk-xxx
```

Dockerfile：

```
FROM ubuntu:latest

ARG TARGETARCH

ENV GBP_USER ${GBP_USER:-ubuntu}
ENV GBP_USER_ID ${GBP_USER_ID:-1000}

WORKDIR /app

USER root

RUN apt-get update && apt-get install -y --no-install-recommends curl ca-certificates

RUN curl -L https://github.com/Harry-zklcdc/go-bingai-pass/releases/latest/download/go-bingai-pass-linux-${TARGETARCH}.tar.gz -o go-bingai-pass-linux.tar.gz && \
    tar -zxvf go-bingai-pass-linux.tar.gz && \
    chmod +x go-bingai-pass

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm go-bingai-pass-linux.tar.gz

USER $GBP_USER

ENV PORT=7860

EXPOSE 7860

CMD /app/go-bingai-pass
```

### Expected behavior

期望在部署完成后不显示盗版

### Deploy

Docker

### UserId

10tpo06

### OS & Version

Windows 11

### Browser & Version

Microsoft Edge 版本 125.0.2535.67 (正式版本) (64 位)

### GoProxiBingAI Version

v2.4.3
